"""Добавил комменты к дедлайнам

Revision ID: ad1163c41af0
Revises: d073b542d6d7
Create Date: 2026-10-05 18:31:21.792542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad1163c41af0'
down_revision: Union[str, Sequence[str], None] = 'd073b542d6d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deadlines', sa.Column('comment', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deadlines', 'comment')
    # ### end Alembic commands ###
