"""Добавил время создания задачи(чисто по приколу) и сделал фамилию необязательным пунктом

Revision ID: 9122af4dd5f7
Revises: ab26b59a6a40
Create Date: 2026-09-29 12:11:42.556377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9122af4dd5f7'
down_revision: Union[str, Sequence[str], None] = 'ab26b59a6a40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('creation_time', sa.DateTime(), nullable=False))
    op.alter_column('users', 'surname',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'surname',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.drop_column('events', 'creation_time')
    # ### end Alembic commands ###
