"""Вернул модель task, добавил модель deadline

Revision ID: d073b542d6d7
Revises: 25586d645418
Create Date: 2026-09-30 23:09:32.297492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd073b542d6d7'
down_revision: Union[str, Sequence[str], None] = '25586d645418'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deadlines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('expire_date', sa.Date(), nullable=True),
    sa.Column('repeat', sa.Boolean(), nullable=False),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', 'VERY_HARD', name='difficulty'), nullable=True),
    sa.Column('tag', sa.String(length=30), nullable=True),
    sa.Column('send_notification', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('potential_duration', sa.Integer(), nullable=True),
    sa.Column('actual_duration', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('potential_end_time', sa.Time(), nullable=True),
    sa.Column('task_date', sa.Date(), nullable=True),
    sa.Column('creation_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('events', sa.Column('event_date', sa.Date(), nullable=False))
    op.drop_column('events', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('events', 'event_date')
    op.drop_table('tasks')
    op.drop_table('deadlines')
    # ### end Alembic commands ###
