"""Каскад при удалении пользователя и nullable=False в user_id

Revision ID: 3ac9fc46f116
Revises: c2e49068080b
Create Date: 2026-09-29 17:49:59.338870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ac9fc46f116'
down_revision: Union[str, Sequence[str], None] = 'c2e49068080b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
