"""Добавил сон v1

Revision ID: 25586d645418
Revises: 8f8a7cf2a1f1
Create Date: 2026-09-30 21:32:24.262312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25586d645418'
down_revision: Union[str, Sequence[str], None] = '8f8a7cf2a1f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sleep_time_hours', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('go_to_sleep_time', sa.Time(), nullable=True))
    op.add_column('users', sa.Column('wake_up_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'wake_up_time')
    op.drop_column('users', 'go_to_sleep_time')
    op.drop_column('users', 'sleep_time_hours')
    # ### end Alembic commands ###
