"""В модели события добавил поля актуальной длительности события, времени начала, потенциального времени окончания и немного поправил уже существующие поля с datetime

Revision ID: c2e49068080b
Revises: 9122af4dd5f7
Create Date: 2026-09-29 13:43:40.261535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c2e49068080b'
down_revision: Union[str, Sequence[str], None] = '9122af4dd5f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('actual_duration', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('start_time', sa.DateTime(timezone=True), nullable=False))
    op.add_column('events', sa.Column('potential_end_time', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('events', 'potential_duration',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('events', 'creation_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'creation_time',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('events', 'potential_duration',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('events', 'potential_end_time')
    op.drop_column('events', 'start_time')
    op.drop_column('events', 'actual_duration')
    # ### end Alembic commands ###
