"""Модель tasks, разграничил события и задачи, сделал отличающийся функционал, также разграничил datetim от date и time

Revision ID: 8f8a7cf2a1f1
Revises: 3ac9fc46f116
Create Date: 2026-09-30 21:18:10.120094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f8a7cf2a1f1'
down_revision: Union[str, Sequence[str], None] = '3ac9fc46f116'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('end_time', sa.Time(), nullable=True))
    op.alter_column('events', 'start_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Time(),
               existing_nullable=False)
    op.alter_column('events', 'date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Date(),
               existing_nullable=False)
    op.drop_column('events', 'potential_duration')
    op.drop_column('events', 'actual_duration')
    op.drop_column('events', 'potential_end_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('potential_end_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('events', sa.Column('actual_duration', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('potential_duration', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('events', 'date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('events', 'start_time',
               existing_type=sa.Time(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_column('events', 'end_time')
    # ### end Alembic commands ###
